### ISSUE TITLE
Key Combinations?

### ISSUE THREAD

**Issue by karimawi** [Sandoramix/SpotiShortcut#2]
seems like I can't use 2 keys combined as a shortcut, the easiest approach I see can be done is to check for a "+" in the key, and split the key string to: before the "+" and after the "+".

For example if the shortcut is:
```addToLiked: alt+a```

you can then list(key), do a for loop for the length of the list which checks if list[index] == "+" else: key = join.list()
then save the index of the "+" if exists, take what's before it as the first key in the combination and take what's after it as the second key in the combination, and then modify the condition in listener() to check for the 2nd key along with the 1st if there's a second one

Theres's probably an easier way to do that, but I just simply suck, and I couldn't do it myself and request a pull because I'm so bad at tracing because I'm still learning and I'm only familiar with a few libs out there, anyway, great job man.

**Comment by sandoramix** [comment]
i got you, now you can make them with this syntax -> \<key\>+\<key2\>
